//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_ten.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_History
    {
        public int History_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
